resources:
  - name: main
    type: git
    source:
      uri: https://github.com/dataplayground/restSimple.git
      branch: master
  - name: dev
    type: git
    source:
      uri: https://github.com/dataplayground/restSimple.git
      branch: develop

  - name: final-release
    type: git
    source:
      uri: https://github.com/dataplayground/restSimple.git
      branch: master
  - name: gh-release
    type: github-release
    source:
      user: dataplayground
      repository: restSimple
      access_token: {{github-access-token}}
  - name: dockerhub
    type: docker-image
    source:
      repository: dataplayground/rest
      username: {{docker-username}}
      email: {{docker-email}}
      password: {{docker-password}}

jobs:
  - name: worker-main
    plan:
      - get: main
      - task: unit
        file: main/ci/unit.yml
  - name: worker-dev
    plan:
      - get: dev
      - task: unit
        file: dev/ci/unit.yml

  # - name: deploy1
  #   serial: true
  #   plan:
  #     - aggregate:
  #         - get: main
  #           passed: [worker-main]
  #     - task: deploy
  #       file: main/ci/deploy.yml
  #     - put: final-release
  #       params:
  #         from: deploy/release/build/*.tgz
  # - name: deploy2
  #   serial: true
  #   plan:
  #     - aggregate:
  #         - get: main
  #           passed: [worker-main]
  #     - task: deploy-gh
  #       file: main/ci/deploy-gh.yml
  #     - put: gh-release
  #       params:
  #         name: fooBarTest
  #         tag: 1.0-test
  #         body: path/to/body/file
  #         globs:
  #           - deploy-gh/*.tgz

  - name: deploy3
    serial: true
    plan:
      - get: main
      passed: [worker-main]
      - put: docker-hub
      params: {build: main}

groups:
- name: overview
  jobs:
  - worker-main
  - worker-dev
 # - deploy1
  #- deploy2
  - deploy3
- name: tests
  jobs:
  - worker-main
  - worker-dev
 - name: deploy
   jobs:
#   - deploy1
#   - deploy2
   - deploy3
